#!/bin/bash

# HRRR Data Extraction - Quick Setup Script
# This script helps set up the Docker environment for HRRR data extraction

echo "HRRR Data Extraction - Quick Setup"
echo "=================================="

# Get current directory
CURRENT_DIR=$(pwd)
SCRIPTS_DIR="$CURRENT_DIR/scripts"
DATA_DIR="$CURRENT_DIR/data"

echo "Current directory: $CURRENT_DIR"

# Check if we're in the right directory
if [[ ! -f "docker-compose.yml" ]] || [[ ! -d "scripts" ]]; then
    echo "❌ Error: Please run this script from the hrrr-deploy root directory"
    echo "   Expected files: docker-compose.yml, scripts/"
    exit 1
fi

# Create .env file if it doesn't exist
if [[ ! -f ".env" ]]; then
    echo "📝 Creating .env file..."
    cat > .env << EOF
# HRRR Data Extraction - Docker Compose Configuration
# Generated by setup script on $(date)

# HOST PATHS (relative to project directory)
HOST_SCRIPT_ABS_DIR=./scripts
HOST_DATA_ABS_DIR=./data

# EXTRACTION COMMAND
# Default: Full extraction (Feb 19, 2015 - Mar 6, 2021)
RUN_COMMAND=/opt/aws-process-hrrr.sh

# Alternative commands (uncomment to use):
# Single day test:
# RUN_COMMAND=/opt/aws-process-hrrr.sh 20200101 20200101
# Custom date range:
# RUN_COMMAND=/opt/aws-process-hrrr.sh 20150219 20150228

# AWS Configuration
AWS_DEFAULT_REGION=us-east-1
EOF
    echo "✅ Created .env file with relative paths:"
    echo "   Scripts: ./scripts"
    echo "   Data: ./data"
else
    echo "✅ .env file already exists"
fi

# Create data directories
echo "📁 Creating data directories..."
mkdir -p "$DATA_DIR"/{download,output,archive,logs,analysis}
echo "✅ Created data directory structure in $DATA_DIR"

# Check Docker
echo "🐳 Checking Docker..."
if command -v docker &> /dev/null && command -v docker-compose &> /dev/null; then
    echo "✅ Docker and Docker Compose found"
    
    # Check if Docker is running
    if docker info &> /dev/null; then
        echo "✅ Docker daemon is running"
    else
        echo "❌ Docker daemon is not running. Please start Docker first."
        exit 1
    fi
else
    echo "❌ Docker or Docker Compose not found. Please install Docker first."
    exit 1
fi

echo ""
echo "🚀 Setup Complete!"
echo "=================="
echo ""
echo "Next steps:"
echo "1. Review/edit .env file if needed:"
echo "   nano .env"
echo ""
echo "2. Run validation test:"
echo "   docker-compose run --rm wgrib2 /opt/validate-setup.sh"
echo ""
echo "3. Run single day test:"
echo "   # Edit .env to set: RUN_COMMAND=/opt/aws-process-hrrr.sh 20200101 20200101"
echo "   docker-compose up"
echo ""
echo "4. Run full extraction (will take 2-4 weeks):"
echo "   # Edit .env to set: RUN_COMMAND=/opt/aws-process-hrrr.sh"
echo "   docker-compose up"
echo ""
echo "Data will be saved to: $DATA_DIR"
echo "Monitor progress: tail -f ./data/logs/hrrr-prate-oso-creek-*.log"
