#!/usr/bin/env python3

"""Convert wgrib2 output (as generated by aws-process-hrrr.sh) into a [hopefully] more useful CSV format.
"""

import os
from datetime import datetime, timezone, timedelta
import dateparser
import pytz
from dotenv import load_dotenv
import re
import argparse
from distutils.util import strtobool
import json
import zipfile
import io
from pathlib import Path

# All for logging?
import logging
import time
import platform
import sys

import boto3
from botocore.exceptions import ClientError

from typing import List, Dict

# Column ordering
csv_col_order:List[str] = ()

# Output log messages w/ [UTC] times in ISO 8601 format and host, program, pid too
logging.Formatter.converter = time.gmtime  # log message times in GMT/UTC
host:str = platform.uname().node            # cross-platform hostname
logging.basicConfig(format='#%(asctime)s {0} {1}[{2}] %(levelname)s:%(message)s'.format(host, os.path.basename(sys.argv[0]), os.getpid()), datefmt='%Y-%m-%dT%H:%M:%SZ')
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)


def build_loc_columns(d:Dict[str,str]):
    """Construct column header list for locations"""
    my_list:List[str] = list(d.keys())
    my_list.sort()
    return my_list


def parse_lon_output(s:str):
    """Convert value at location string from wgrib2 into ["LatLon_$lat_$lon", "val"]:

        'lon=262.734337,lat=27.660547,val=0' → ['LatLon_27.660547_262.734337', '0']

    FMI https://www.cpc.ncep.noaa.gov/products/wesley/wgrib2/lon.html
    """
    m = re.search(r'^lon=([\d.]+),lat=([\d.]+),val=(-?[\d.]+(?:e[+-]\d+)?)$', s)
    # Throw error if we don't match?!  (unexpected format)
    if (not m):
        logger.error(f'Don\'t know how to parse [value] "{s}"')
    return [f'LatLon_{m[2]}_{m[1]}', m[3]]


def config2locations(c):
    """  '<lon>,<lat>': 'KRCP_ul'
    """
    # TODO  Code here !
    return


def download_objects(s3client, objs):
    """Download objects supplied in list_objects_v2() response from S3 bucket.
    """

    # TODO  Make sure os.getenv('HRRR_DOWNLOAD_PATH') exists and is a directory/writeable?

    # Not sure if there's a better way to access this stuff other than directly yanking out of the response dictionary?
    bucket: str = objs['Name']
    s3_keys: List[str] = [ o['Key'] for o in objs['Contents'] ]
    fqpns: List[str] = []               # list of filenames to process

    logger.info(f'Checking and downloading objects from S3 bucket "{bucket}" matching prefix "{objs["Prefix"]}":')
    for k in s3_keys:
        response = s3client.head_object(Bucket=bucket,Key=k)
        s3_size:int = response['ContentLength']
        s3_lm_time:int = int(response['LastModified'].timestamp())

        dest_fqpn: str = os.getenv('HRRR_DOWNLOAD_PATH') + f'/{k}'

        if os.path.isfile(dest_fqpn):
            # Check on-disk file size and modification time to verify it matches/exceeds whats in S3
            # Note 6
            stat = os.stat(dest_fqpn)
            if stat.st_size == s3_size and stat.st_mtime >= s3_lm_time:
                logger.info(f' • File "{k}" already on system ({dest_fqpn}), skipping download')
                fqpns.append(dest_fqpn)
                continue
            else:
                logger.info(f' • File "{k}" already on system ({dest_fqpn}) doesn\'t match S3 object, downloading again')
        logger.info(f' • Downloading file "{k}" → {dest_fqpn}')
        # Try/catch block stolen from
        # https://boto3.amazonaws.com/v1/documentation/api/1.9.42/guide/s3-example-download-file.html
        try:
            s3client.download_file(bucket, k, dest_fqpn)
        except ClientError as e:
            if e.response['Error']['Code'] == "404":
                errmsg: str = f'S3 object "{k}" does not exist.'
                logger.error(f' • {errmsg}')
                # TODO  How to handle error?!
                #raise PCProcessingException(errmsg, pc)
            # TODO  Handle/dump other ClientError(s) here?  See e.message
            else:
                raise

        # Add successfully d/l'd object to list of files to process
        fqpns.append(dest_fqpn)
    return fqpns


def process_file(filename:str):
    """Parse [zipped] file[name] containing wgrib2 output and output CSV
       w/ locations mapped to columns

    Expects wgrib2 run w/ the following flags:
        -T          show reference time
        -var        short variable name?
        -lev        print level of field
        -ftime      print forecast timestamp
    """
    global csv_col_order

    # TODO  Throw exception if filename doesn't end in .zip ?!

    counter:int = 0
    utc = pytz.utc
    with zipfile.ZipFile(filename, mode='r') as wgrib2_zip:
        for zfn in wgrib2_zip.namelist():
            logger.info(f'Processing {zfn} in archive file {filename}')
            with wgrib2_zip.open(zfn, mode='r') as wgrib2_text:
                # Zipfile seems to force binary [file I/O] mode?  Have to throw a wrapper around it to act as if it's plain text
                # FMI  https://stackoverflow.com/a/5639960/1502174
                for line in io.TextIOWrapper(wgrib2_text):
                    line = line.rstrip()
                    msg, byteloc, reference_time, var, level, ftime, values_str = line.split(':',6)

                    # Have to explictly set timezone to UTC otherwise it will assume [system] local timezone
                    reference_dt = utc.localize(datetime.strptime(reference_time, "D=%Y%m%d%H%M%S"))

                    # Parse forecast time
                    # ftime =~ :( anl | \d+ hr fcst ):                  // simple
                    # ftime ~= :(?:day|hour) (?:min|max|ave|acc) fcst:  // complicated
                    # FMI  https://www.cpc.ncep.noaa.gov/products/wesley/wgrib2/ftime.html
                    ftime_col:str = ''
                    ptime_col:str = ''

                    # XXX  For [Niall's] future reference:
                    #
                    #    Capture/group numbering works differently than I thought it would:
                    #    Assuming regular expression is '^(?:(anl)|(\d+) hour fcst)$'
                    #      - If present, "anl" will be put in match[1] (AKA match.group(1)).
                    #      - If "\d+ hour fcst" is found, the number will be in match[2] (AKA match.group(2))
                    match = re.match('^(?:(anl)|(\d+) hour fcst)$', ftime)
                    if match:
                        ftime_col = '0' if (match.group(0) == 'anl') else match.group(2)
                        prediction_dt = reference_dt + timedelta(hours=int(ftime_col))
                        ptime_col = prediction_dt.isoformat()
                    else:
                        # These are rather complicated description/forecast strings, not sure how/if to reduce (or exclude?)
                        if (re.match('^\d+-\d+ (?:day|hour) (?:min|max|ave|acc) fcst$', ftime)):
                            ftime_col = ftime
                        else:
                            # TODO  Throw error (unknown/unrecognized format)
                            logger.error(f'Don\'t know how to parse [forecast time] "{s}"')
                            pass

                    # TODO  Parse level?

                    # Map lat,lon coordinates to values
                    loc2val:Dict[str,str] = { k:v for (k,v) in
                            [ parse_lon_output(elem) for elem in values_str.split(':') ]
                        }

                    # Column headers sanity check(s)
                    if (len(csv_col_order) == 0):
                        csv_col_order = build_loc_columns(loc2val)
                        # Print header (once)
                        header:str = 'cycle_date,forecast_hour,prediction_date,series,level,' + ','.join(csv_col_order)
                        print(header)
                    if (len(csv_col_order) != len(loc2val)):
                        # Error!  More data positions than Locations in header
                        # Vice versa (more header locations than data) may _not_ be an error
                        # TODO  Throw error?
                        logger.error(f'Unequal amount of location columns ({len(csv_col_order)}) and location values in [wgrib2] data ({len(loc2val)}! ')

                    # Emit row
                    # cycle_date[time], forecast_hour, prediction_date[time], series, [locations]
                    row:List[str] = [
                            reference_dt.isoformat(),
                            ftime_col,
                            ptime_col,
                            var,
                            level
                        ]
                    row.extend([ loc2val[k] for k in csv_col_order ])
                    print(','.join(row))


def main():
    """Setup processing and loop over date range."""
    load_dotenv()

    # Parse CLI arguments
    # TODO  CLI argument: Time period of output files (daily, monthly)?
    # TODO  CLI argument: Specify directory to output files?
    parser = argparse.ArgumentParser(description=__doc__)
    # TODO  CLI argument to remove working files (default keep)
    #parser.add_argument('--preserve', help='Keep downloaded wgrib2 output files after processing')
    # See https://www.pythonpool.com/python-argparse-boolean/#h-code-4-parsing-arguments-using-distuils-module
    #parser.add_argument('--remove', type=lambda x:bool(strtobool(x)), nargs='?', const=True, default=False, help='Remove downloaded wgrib2 output files after processing (default keep)')
    parser.add_argument('--config', type=str, default='hrrr-locations.json', help='JSON filename with location configuration information')
    parser.add_argument('begin_date', type=str, help='Date to start processing output')
    parser.add_argument('end_date', type=str, help='Date to stop processing output (inclusive)')
    arguments = parser.parse_args()

    # Date range checks
    begin_dt:datetime = dateparser.parse(arguments.begin_date)
    end_dt:datetime = dateparser.parse(arguments.end_date)
    if (not begin_dt or not end_dt):
        logger.error(f'Unable to properly parse begin date "{arguments.begin_date}" and/or end date "{arguments.end_date}".  YYYY-MM-DD and MM/DD/YYYY should work')
        return
    if end_dt < begin_dt:
        logger.error(f'End date ({arguments.end_date} ⇒ {end_dt}) is _before_ begin date ({arguments.begin_date} ⇒ {begin_dt}).  Is there a typo in the specified dates?  YYYY-MM-DD and MM/DD/YYYY should work')
        return

    # Just in case (date paranoia)
    begin_dt = begin_dt.replace(hour=0, minute=0)
    end_dt = end_dt.replace(hour=23, minute=59)
    logger.info(f'Processing HRRR results from {begin_dt} to {end_dt} (inclusive)')

    # TODO  Parse config file [Locations ± output file] for location demultiplexing?
    #print (f'config file {arguments.config}') # XXX REMOVE
    #with open(arguments.config) as f:
    #    config = json.load(f)
    #print (config['locations']['KCRP']) # XXX  REMOVE

    # Make sure [necessary] directory structure exists
    # From https://stackoverflow.com/a/273227/1502174
    for v in [ 'HRRR_DOWNLOAD_PATH', 'HRRR_OUTPUT_PATH', 'HRRR_ARCHIVE_PATH', 'HRRR_LOG_PATH' ]:
        pathname:str = os.getenv(v)
        if pathname:
            Path(pathname).mkdir(parents=True, exist_ok=True)

    # Setup AWS resources
    s3client = boto3.client('s3')
    bucket_name:str = os.getenv('HRRR_OUTPUT_BUCKET').replace('s3://','')

    # Loop over desired date range, processing one day at a time
    loop_dt:datetime = begin_dt
    while loop_dt < end_dt:
        ymd_prefix:str = loop_dt.strftime('%Y%m%d')
        logger.info(f'Processing day {ymd_prefix}')
        s3_objs = s3client.list_objects_v2(Bucket=bucket_name,Prefix=ymd_prefix)
        filenames:List[str] = download_objects(s3client, s3_objs)
        # Convert wgrib2 output to CSV
        for fn in filenames:
            process_file(fn)
        loop_dt += timedelta(days=1)

    # TODO  Clean up working files unless they want to keep


if __name__ == '__main__':
    main()
